// <auto-generated />
namespace DMH_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bang));
        
        string IMigrationMetadata.Id
        {
            get { return "202303060638386_Bang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
